# Global Well-Being:
## Exploring the Relationship Between Mental Health, Economic Factors, and Happiness

### Author
Rebecca Rader 

### Project Overview

This project investigates how economic conditions, mental health resources, and social factors relate to national happiness and mental health outcomes across countries. Using data from two global datasets, the analysis explores whether factors such as GDP, access to mental health care, and social media usage are associated with differences in happiness and mental health across nations.

In [3]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# SQLite
import sqlite3

# Display graphs inside notebook
%matplotlib inline

In [4]:
df = pd.read_csv("../data/cleaned/mental_health_combined.csv")

In [5]:
df.head()

,country,iso3,region,income_group,depression_pct,anxiety_pct,suicide_rate_per_100k,psychiatrists_per100k,mh_budget_pct_of_health_spending,mh_spend_per_capita_usd,...,data_year,data_source,Overall rank,happiness_score,gdp_per_capita_usd_y,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Malawi,MWI,Africa,Low,3.3,4.5,6.5,0.02,0.8,0.1,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,150.0,3.410,0.191,0.560,0.495,0.443,0.218,0.089
1,Mozambique,MOZ,Africa,Low,3.4,4.6,8.2,0.04,0.6,0.1,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,123.0,4.466,0.204,0.986,0.390,0.494,0.197,0.138
2,Ethiopia,ETH,Africa,Low,3.5,4.8,10.2,0.04,1.0,0.1,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,134.0,4.286,0.336,1.033,0.532,0.344,0.209,0.100
3,Zimbabwe,ZWE,Africa,Low,4.0,5.2,15.4,0.05,0.7,0.1,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,146.0,3.663,0.366,1.114,0.433,0.361,0.151,0.089
4,Tanzania,TZA,Africa,Low,3.6,4.9,8.6,0.04,0.8,0.1,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,153.0,3.231,0.476,0.885,0.499,0.417,0.276,0.147

In [6]:
df.tail()

,country,iso3,region,income_group,depression_pct,anxiety_pct,suicide_rate_per_100k,psychiatrists_per100k,mh_budget_pct_of_health_spending,mh_spend_per_capita_usd,...,data_year,data_source,Overall rank,happiness_score,gdp_per_capita_usd_y,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
87,Sweden,SWE,Europe,High,4.6,4.8,13.9,26.8,10.2,165.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,7.0,7.343,1.387,1.487,1.009,0.574,0.267,0.373
88,Denmark,DNK,Europe,High,4.7,4.9,11.3,19.4,8.9,178.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
89,Singapore,SGP,W. Pacific,High,3.5,4.8,9.2,8.6,6.4,82.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,34.0,6.262,1.572,1.463,1.141,0.556,0.271,0.453
90,Switzerland,CHE,Europe,High,4.4,4.7,12.2,54.9,8.2,320.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
91,Norway,NOR,Europe,High,4.5,4.6,12.6,31.0,9.8,210.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341

In [7]:
df.shape

(92, 37)

In [8]:
df.columns

Index(['country', 'iso3', 'region', 'income_group', 'depression_pct',
       'anxiety_pct', 'suicide_rate_per_100k', 'psychiatrists_per100k',
       'mh_budget_pct_of_health_spending', 'mh_spend_per_capita_usd',
       'treatment_gap_pct', 'social_media_hours_daily',
       'internet_penetration_pct', 'gdp_per_capita_usd_x',
       'population_millions', 'covid_mh_increase_pct', 'youth_mh_crisis_score',
       'has_mh_policy', 'has_mh_law', 'mental_health_crisis_index',
       'total_affected_millions', 'psychiatrists_per_million',
       'mh_investment_gap', 'social_media_mental_health_risk',
       'depression_anxiety_comorbidity_est_pct', 'mh_system_score',
       'income_group_code', 'data_year', 'data_source', 'Overall rank',
       'happiness_score', 'gdp_per_capita_usd_y', 'Social support',
       'Healthy life expectancy', 'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 37 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   country                                 92 non-null     str
 1   iso3                                    92 non-null     str
 2   region                                  92 non-null     str
 3   income_group                            92 non-null     str
 4   depression_pct                          92 non-null     float64
 5   anxiety_pct                             92 non-null     float64
 6   suicide_rate_per_100k                   92 non-null     float64
 7   psychiatrists_per100k                   92 non-null     float64
 8   mh_budget_pct_of_health_spending        92 non-null     float64
 9   mh_spend_per_capita_usd                 92 non-null     float64
 10  treatment_gap_pct                       92 non-null     float64
 11  social_media_hours_daily                92 non-null     float64
 12  internet_penetration_pct                92 non-null     float64
 13  gdp_per_capita_usd_x                    92 non-null     int64
 14  population_millions                     92 non-null     float64
 15  covid_mh_increase_pct                   92 non-null     float64
 16  youth_mh_crisis_score                   92 non-null     float64
 17  has_mh_policy                           92 non-null     int64
 18  has_mh_law                              92 non-null     int64
 19  mental_health_crisis_index              92 non-null     int64
 20  total_affected_millions                 92 non-null     float64
 21  psychiatrists_per_million               92 non-null     float64
 22  mh_investment_gap                       92 non-null     float64
 23  social_media_mental_health_risk         92 non-null     str
 24  depression_anxiety_comorbidity_est_pct  92 non-null     float64
 25  mh_system_score                         92 non-null     float64
 26  income_group_code                       92 non-null     int64
 27  data_year                               92 non-null     int64
 28  data_source                             92 non-null     str
 29  Overall rank                            85 non-null     float64
 30  happiness_score                         85 non-null     float64
 31  gdp_per_capita_usd_y                    85 non-null     float64
 32  Social support                          85 non-null     float64
 33  Healthy life expectancy                 85 non-null     float64
 34  Freedom to make life choices            85 non-null     float64
 35  Generosity                              85 non-null     float64
 36  Perceptions of corruption               85 non-null     float64
dtypes: float64(25), int64(6), str(6)
memory usage: 26.7 KB

In [10]:
df["has_mh_policy"] = df["has_mh_policy"].astype(bool)

In [11]:
df["has_mh_law"] = df["has_mh_law"].astype(bool)

In [12]:
(df["gdp_per_capita_usd_x"] == df["gdp_per_capita_usd_y"]).all()

np.False_

In [13]:
df[["gdp_per_capita_usd_x", "gdp_per_capita_usd_y"]].describe()

       gdp_per_capita_usd_x  gdp_per_capita_usd_y
count             92.000000             85.000000
mean           22231.608696              1.028612
std            25685.337791              0.330628
min              600.000000              0.191000
25%             3975.000000              0.820000
50%            10150.000000              1.050000
75%            33975.000000              1.301000
max           106900.000000              1.572000

In [14]:
df[[
    "country",
    "gdp_per_capita_usd_x",
    "gdp_per_capita_usd_y"
]].head(10)

      country  gdp_per_capita_usd_x  gdp_per_capita_usd_y
0      Malawi                   700                 0.191
1  Mozambique                   600                 0.204
2    Ethiopia                  1200                 0.336
3    Zimbabwe                  1000                 0.366
4    Tanzania                  1200                 0.476
5      Uganda                   900                 0.332
6     Lesotho                  1200                 0.489
7    Eswatini                  4200                   NaN
8     Ukraine                  4108                 0.820
9     Nigeria                  2200                 0.696

In [15]:
df = df.rename(columns={
    "gdp_per_capita_usd_x": "gdp_per_capita_usd",
    "gdp_per_capita_usd_y": "happiness_gdp_factor"
})

In [16]:
df = df.rename(columns={
    "Overall rank": "overall_rank",
    "Social support": "social_support",
    "Healthy life expectancy": "healthy_life_expectancy",
    "Freedom to make life choices": "freedom_to_make_life_choices",
    "Perceptions of corruption": "perceptions_of_corruption"
})

In [17]:
df.describe()

,depression_pct,anxiety_pct,suicide_rate_per_100k,psychiatrists_per100k,mh_budget_pct_of_health_spending,mh_spend_per_capita_usd,treatment_gap_pct,social_media_hours_daily,internet_penetration_pct,gdp_per_capita_usd,...,income_group_code,data_year,overall_rank,happiness_score,happiness_gdp_factor,social_support,healthy_life_expectancy,freedom_to_make_life_choices,Generosity,perceptions_of_corruption
count,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,...,92.000000,92.0,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000
mean,4.402174,5.632609,11.559783,7.182283,3.758696,38.951087,58.934783,2.209783,73.750000,22231.608696,...,2.923913,2025.0,67.917647,5.690247,1.028612,1.287647,0.808824,0.423659,0.182835,0.125165
std,0.754471,1.201657,9.825511,9.485814,2.960366,63.418593,27.884694,0.786711,24.262133,25685.337791,...,1.008030,0.0,45.130027,1.106188,0.330628,0.238595,0.203602,0.125802,0.106557,0.108770
min,2.900000,3.800000,3.200000,0.020000,0.600000,0.100000,17.000000,0.100000,8.000000,600.000000,...,1.000000,2025.0,1.000000,3.231000,0.191000,0.560000,0.168000,0.067000,0.000000,0.005000
25%,3.800000,4.800000,7.575000,0.500000,1.200000,0.725000,26.000000,1.600000,68.750000,3975.000000,...,2.000000,2025.0,26.000000,4.722000,0.820000,1.147000,0.706000,0.351000,0.099000,0.050000
50%,4.400000,5.200000,9.800000,3.150000,2.850000,8.000000,64.500000,2.100000,82.500000,10150.000000,...,3.000000,2025.0,65.000000,5.697000,1.050000,1.360000,0.828000,0.443000,0.160000,0.089000
75%,4.900000,6.100000,12.825000,12.450000,5.650000,49.750000,84.500000,2.800000,92.250000,33975.000000,...,4.000000,2025.0,106.000000,6.444000,1.301000,1.475000,0.987000,0.516000,0.260000,0.161000
max,6.300000,9.300000,87.500000,54.900000,11.300000,320.000000,97.000000,4.800000,99.000000,106900.000000,...,4.000000,2025.0,153.000000,7.769000,1.572000,1.587000,1.141000,0.631000,0.566000,0.453000

In [18]:
df.describe(include="object")

C:\Users\Otters4Life\AppData\Local\Temp\ipykernel_2368\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,country,iso3,region,income_group,social_media_mental_health_risk,data_source
count,92,92,92,92,92,92
unique,92,92,6,4,4,1
top,Malawi,MWI,Europe,High,Moderate (1.5-2.5h),WHO Mental Health Atlas 2024 | GBD Study 2023 ...
freq,1,1,32,35,44,92

In [19]:
df.sample(5)

,country,iso3,region,income_group,depression_pct,anxiety_pct,suicide_rate_per_100k,psychiatrists_per100k,mh_budget_pct_of_health_spending,mh_spend_per_capita_usd,...,data_year,data_source,overall_rank,happiness_score,happiness_gdp_factor,social_support,healthy_life_expectancy,freedom_to_make_life_choices,Generosity,perceptions_of_corruption
58,Saudi Arabia,SAU,E. Med,High,3.4,6.8,3.5,3.80,4.2,28.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,28.0,6.375,1.403,1.357,0.795,0.439,0.080,0.132
82,Finland,FIN,Europe,High,5.6,5.8,14.6,27.60,11.3,195.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393
86,Netherlands,NLD,Europe,High,4.8,5.0,10.8,15.80,8.1,118.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,5.0,7.488,1.396,1.522,0.999,0.557,0.322,0.298
3,Zimbabwe,ZWE,Africa,Low,4.0,5.2,15.4,0.05,0.7,0.1,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,146.0,3.663,0.366,1.114,0.433,0.361,0.151,0.089
8,Ukraine,UKR,Europe,Upper-Middle,6.3,7.1,18.5,3.10,2.8,8.0,...,2025,WHO Mental Health Atlas 2024 | GBD Study 2023 ...,133.0,4.332,0.820,1.390,0.739,0.178,0.187,0.010